### PR TITLE
Player movement

### PR DESCRIPTION
**Pull request by ZeerakBaig-BBD**
Added basic player movement without animations

### CODE REVIEW

**Comment by matt-Kretschmer** [comment]
gg merged

**Comment by matt-Kretschmer** [comment]
Git you killed

**Comment by matt-Kretschmer** [comment]
git merge

**Comment by matt-Kretschmer** [comment]
See this adam

**Comment by matt-Kretschmer** [comment]
look adam

**Comment by Adam-Kaminski-BBD** [comment]
Skiets he move

**Comment by matt-Kretschmer** [comment]
check your email

**Comment by matt-Kretschmer** [comment]
You wasted 5 seconds looking here

**Comment by matt-Kretschmer** [comment]
Check again bru

**Comment by matt-Kretschmer** [comment]
Unlimited power

**Comment by matt-Kretschmer** [comment]
I get none of these

**Comment by matt-Kretschmer** [comment]
!important

**Pull request merged**
